### ISSUE TITLE
Get an error when switching theme

### ISSUE THREAD

**Issue by LmanTW** [zaldih/themery.nvim#14]
This error occurs when trying to switch the theme:
`Themery error: Could not open file for read: /Users/lukelin/v:null`

Operating System: MacOS 10.15.7
Neovim Version: v0.10.0

**Comment by zaldih** [comment]
Thank you for opening this issue.

It seems to be a problem with the **themeConfigFile** parameter. Does the path exist?

Alternatively, I suggest trying the following:
Could you try using this branch and see if the problem is solved? _(Remember to delete the plugin before to update it)_

```lua
Plug 'zaldih/themery.nvim', { 'branch': 'simplify-persistence' }
```

More info #11

**Comment by LmanTW** [comment]
The branch `simplify-persistence` works perfectly!

Also I found out it's because I didn't set the `themeConfigFile` option (didn't read the document fully, my bad), thanks for helping tho! I appreciate it.

**Comment by zaldih** [comment]
Yay!

Thank you very much for trying it out.

It's not your fault. As I said in the other issue, I think the configuration process is confusing. That's why I'm going to merge the branch to main for good and take a look at all the documentation.

Later on, it's possible that your manager will give you a problem when merge and delete the branch. When that happens go back to configuring main or the new release tag :)

Cheers!
