### ISSUE TITLE
Pressing `q` or `<Esc>` does not exit picker

### ISSUE THREAD

**Issue by vince-carpino** [zaldih/themery.nvim#7]
<img width="2032" alt="image" src="https://github.com/zaldih/themery.nvim/assets/25288632/11a04909-045e-4ce8-b0ba-939e21760622">

I get the above error whenever I try to quit the picker via `q` or `<Esc>`.

---

Here is my config:

``` lua
-- themery.lua

return {
  'zaldih/themery.nvim',
  priority = 1000,
  opts = {
    themes = {
      'onedark',
      'catppuccin',
      'tokyonight',
    },
    themeConfigFile = '~/.config/nvim/lua/theme.lua',
  },
}
```

``` lua
-- theme.lua

-- Themery block
-- This block will be replaced by Themery.
vim.cmd("colorscheme onedark")
vim.g.theme_id = 1
-- end themery block
```

**Comment by zaldih** [comment]
Thank you for opening this issue!

I have managed to replicate the error. It seems that for some reason the `theme.lua` file does not load (and `vim.g.theme_id` not setted).

**Could you try browsing and selecting a theme from your list**? If the problem is in the path given in `themeConfigFile` it will show an error like the following: _`Themery error: Could not open file for read [...]`_

**Comment by vince-carpino** [comment]
I can select any theme from the list and it previews and applies them all perfectly without error. I see the `Theme saved` message as well.

However, after quitting and relaunching Neovim, it always loads `onedark`, even if I chose a different theme.

**What should each theme plugin file look like?** I've tried commenting out each one's `config` section, as well as setting `config = true`, but in both cases Neovim loads without a colorscheme. In that scenario, I can choose a theme from `:Themery` and it is applied properly _**to that session**_.

I am using [lazy.nvim](https://github.com/folke/lazy.nvim) as my plugin manager.

Here are my theme files:

``` lua
-- onedark.lua

return {
  'navarasu/onedark.nvim',
  priority = 1000,
  config = function()
    vim.cmd.colorscheme('onedark')
  end
}
```

``` lua
-- catppuccin.lua

return {
  'catppuccin/nvim',
  name = 'catppuccin',
  priority = 1000,
  config = function()
    vim.cmd.colorscheme('catppuccin')
  end
}
```

``` lua
-- tokyonight.lua

return {
  'folke/tokyonight.nvim',
  config = true,
}
```

**Comment by paramoNNNN** [comment]
I'm also getting the same error when I try to select a theme

Here's my config:
```lua
require("themery").setup({
	themeConfigFile = "~/.config/nvim/lua/configs/theme.lua",
	themes = {
		{
			name = "Dark",
			colorscheme = "carbonfox",
			before = function()
				require("lualine").setup({
					options = {
						theme = "carbonfox",
					},
				})
			end,
		},
		{
			name = "Light",
			colorscheme = "catppuccin",
			before = function()
				require("lualine").setup({
					options = {
						theme = "catppuccin",
					},
				})
			end,
		},
	},
	livePreview = true,
})
```

And the themery file:
```lua
-- Themery block
-- end themery block
```

https://github.com/zaldih/themery.nvim/assets/29772611/dac67a74-546a-47b4-8bee-10bb0100b5b2

**Comment by zaldih** [comment]
@paramoNNNN  your problem is that the "before" function is not defined as required. Instead it should contain only the body of the function as text. Like this:
```lua
{
  name = "Dark",
  colorscheme = "carbonfox",
  before = [[
    require("lualine").setup({
      options = {
        theme = "carbonfox",
      },
    })
  ]],
},
{
  name = "Light",
  colorscheme = "catppuccin",
  before = [[
    require("lualine").setup({
      options = {
        theme = "catppuccin",
      },
    })
  ]],
},
```

However, as this can be confusing, "66fa8519843bf5b26ab930d5549ac72e9dd531e0" will now check that the file is well defined and report it.
If this still doesn't work, please open a new issue.

**Comment by zaldih** [comment]
@vince-carpino with 1005a58801276d29c4b1e11244cf7631250f9143 I have fixed the main problem that showed an error when pressing ESC if a topic had not been defined before 🎉 .

For your second message, you should leave a empty function in "config" from each topic otherwise they will always run automatically. So, for example for onedark:
```lua
return {
  'navarasu/onedark.nvim',
  priority = 1000,
  config = function() end -- This will prevent call the default "setup". Maybe deleting it will also work
}
```

And leave to Themery manage then:
```lua
themes = {
      'onedark',
      'catppuccin',
      'tokyonight',
    },
```

If the problem persists, you still have questions or you have a new problem, don't hesitate to re-open or open a new issue!
